#!/usr/bin/env bash

# References
# https://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install

# Enable workspaces
# http://askubuntu.com/questions/260510/how-do-i-turn-on-workspaces-why-do-i-only-have-one-workspace

sudo apt-get -y install git
sudo apt-get install ruby

# Enables "open in terminal" from the context menu
# http://askubuntu.com/questions/207442/how-to-add-open-terminal-here-to-nautilus-context-menu
sudo apt-get -y install nautilus-open-terminal

# http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2-3
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get -y install sublime-text-installer

# Jekyil for editing ubuntu pages
#gem install jekyll

# Tools for converting text to pdf
# http://askubuntu.com/a/27112/430572
sudo apt-get install enscript
# http://unix.stackexchange.com/a/17417/122789
sudo apt-get install paps


# Fixes mouse scroll wheel behavior
# http://askubuntu.com/questions/255890/how-can-i-adjust-the-mouse-scroll-speed
wget-P ~/Downloads  http://sourceforge.net/projects/resetmsmice/files/resetmsmice_1.1.2-1_amd64.deb/download 
sudo dpkg -i ~/Downloads/resetmsmice_1.1.2-1_amd64.deb
resetmsmice