#!/usr/bin/env bash

# References
# https://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install

# Enable workspaces
# http://askubuntu.com/questions/260510/how-do-i-turn-on-workspaces-why-do-i-only-have-one-workspace

# Various utilities
sudo apt-get -y install git
sudo apt-get -y install ruby
sudo apt-get -y install xclip

# Enables "open in terminal" from the context menu
# http://askubuntu.com/questions/207442/how-to-add-open-terminal-here-to-nautilus-context-menu
sudo apt-get -y install nautilus-open-terminal

# http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2-3
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get -y install sublime-text-installer

# Tools for converting text to pdf
# http://askubuntu.com/a/27112/430572
sudo apt-get -y install enscript
# http://unix.stackexchange.com/a/17417/122789
sudo apt-get -y install paps


# Fixes mouse scroll wheel behavior
# http://askubuntu.com/questions/255890/how-can-i-adjust-the-mouse-scroll-speed
wget-P ~/Downloads  http://sourceforge.net/projects/resetmsmice/files/resetmsmice_1.1.2-1_amd64.deb/download 
sudo dpkg -i ~/Downloads/resetmsmice_1.1.2-1_amd64.deb
resetmsmice

# Some C++ features depend on later GCC versions on Ubuntu
# http://stackoverflow.com/questions/24990646/how-do-i-use-regex-replace
# http://stackoverflow.com/a/12665408/702828
# http://stackoverflow.com/questions/15615136/is-codecvt-not-a-std-header
# To install newer gcc versions:
# http://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu
# http://askubuntu.com/questions/618474/how-to-install-the-latest-gcurrently-5-1-in-ubuntucurrently-14-04
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get -y install g++-4.9
sudo apt-get -y install g++-5
# After installing, the default version must be configured manually:
# http://askubuntu.com/a/26518/430572
sudo update-alternatives --remove-all gcc 
sudo update-alternatives --remove-all g++
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 30
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 30
sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --set cc /usr/bin/gcc
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set c++ /usr/bin/g++
switch_gcc 5

# https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
# https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
# http://stackoverflow.com/questions/3659602/bash-script-for-generating-ssh-keys
yes "y" | ssh-keygen -t rsa -b 4096 -C "arthurnunesq@gmail.com"