#!/usr/bin/env bash

# Copy files from the devtoolbox as symbolic links to the user bin folder.
# https://superuser.com/a/244647/149826
SRC_DIR=/home/$USER/src/devtoolbox
DST_DIR=/home/$USER/bin

find -L $DST_DIR -maxdepth 1 -type l -delete
ln -f -s $SRC_DIR/* $DST_DIR

